### ISSUE TITLE
Please test major functionality against production

### ISSUE THREAD

**Issue by postfalk** [berkeley-gif/vtm#5]
Funny that you just tested now. Moved this version of the Ecoengine to production just yesterday. Move if it works.

Falk

**Comment by mukhtyar** [comment]
Yes  I tested against production server. Everything works. I was trying to upload compiled project to vtm-dev that points to the production server to confirm. But I cannot access vtm.berkeley.edu:8000, some issue with configuration?

**Comment by postfalk** [comment]
Just talked to Brian, he closed the port after the gis.berkeley.edu snafu.
He will open it again.

Fall

On Fri, Mar 20, 2015 at 11:08 AM, Shruti Mukhtyar <notifications@github.com>
wrote:

> Yes I tested against production server. Everything works. I was trying to
> upload compiled project to vtm-dev that points to the production server to
> confirm. But I cannot access vtm.berkeley.edu:8000, some issue with
> configuration?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/berkeley-gif/vtm/issues/5#issuecomment-84090869>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by mukhtyar** [comment]
All major functionality works against the production server.
