### ISSUE TITLE
http://vtm.berkeley.edu/#/data/vegetation

### ISSUE THREAD

**Issue by postfalk** [berkeley-gif/vtm#6]
Hi Falk,

This is either a typo or a new method. 

http://vtm.berkeley.edu/#/data/vegetation

Text below the map 
"Dominant vegetation type maps were mapped with a minimum mapping unit of 16 ha by direct. "

Should be "direct observation." ?

Let me know because I'm explaining this on Holos. 

Thanks,
Heather

**Comment by postfalk** [comment]
@hconstable you can now directly file issues on this repository.

**Comment by mukhtyar** [comment]
Fixed missing text 'observation'.
