### ISSUE TITLE
Request to change text on http://vtm.berkeley.edu/#/about/

### ISSUE THREAD

**Issue by hconstable** [berkeley-gif/vtm#7]
Hello, 

Staci Markos from UCJeps was reviewing Holos and followed the links to the VTM site. She requested a correction to the text on the VTM about page.

"Additionally, sample specimens were collected and placed in the University Herbarium (now the Jepson Herbarium), many of which remain there today."

That should be changed to: 
"Additionally, sample specimens were collected and placed in the University and Jepson Herbaria (ucjeps.berkeley.edu), many of which remain there today."

Thanks.

**Comment by mukhtyar** [comment]
Fixed text.

**Comment by hconstable** [comment]
Thanks!
